Readme 0813
rte-design/ASTRA.ai pull request #201
Opened 2024-08-13 22:26 UTC by cyfyifanchen

2024-08-14 05:26 UTC, plutoless commented on docs/readmes/README-CN.md
> +打开 `.env` 文件，绑定对应的积木 keys，这里也可以通过配置不同的 keys 选用不用的积木：
建议不要用积木，用extensions

2024-08-19 06:21 UTC, plutoless requested changes

2024-08-19 06:21 UTC, plutoless commented on docs/readmes/README-CN.md
> +export https_proxy=http://127.0.0.1:（端口例如 7890）
容器内要用http://host.docker.internal

2024-08-19 06:31 UTC, wangyoucao577 commented on docs/readmes/README-CN.md
> +export https_proxy=http://127.0.0.1:（端口例如 7890）
mac 和 windows 的 docker 这样都能 work？

2024-08-19 06:41 UTC, cyfyifanchen commented on docs/readmes/README-CN.md
> +export https_proxy=http://127.0.0.1:（端口例如 7890）
@wangyoucao577 mac 可以，windows 应该可以。

2024-08-19 06:42 UTC, cyfyifanchen commented on docs/readmes/README-CN.md
> +export https_proxy=http://127.0.0.1:（端口例如 7890）
windows 可能有更优雅的方法，比如他们说的 Clash for windows 上的 Tun 模式，这种稍后直接写到更详细的 gitbook 上吧。

2024-08-19 07:36 UTC, plutoless approved these changes

2024-08-19 07:36 UTC, merged